<a href="https://colab.research.google.com/github/Abhiram791/BDA-ICP/blob/main/icp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

abhi = np.random.randint(1, 21, size=15)
print("Original Array:\n", abhi)

abhi = abhi.reshape(3, 5)
print("\nReshaped Array (3x5):\n", abhi)

print("\nArray Shape:", abhi.shape)

for i in range(abhi.shape[0]):
    ram = np.argmax(abhi[i])
    abhi[i, ram] = 0

print("\nArray after replacing max in each row by 0:\n", abhi)

Original Array:
 [19 12 18 12 15  2  2  6 10 16 12 13  3  5  4]

Reshaped Array (3x5):
 [[19 12 18 12 15]
 [ 2  2  6 10 16]
 [12 13  3  5  4]]

Array Shape: (3, 5)

Array after replacing max in each row by 0:
 [[ 0 12 18 12 15]
 [ 2  2  6 10  0]
 [12  0  3  5  4]]


In [2]:
arr_b = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]], dtype=np.int32)

print("\nArray (4x3):\n", arr_b)
print("\nShape of the array:", arr_b.shape)
print("Type of the array:", type(arr_b))
print("Data type of the array elements:", arr_b.dtype)


Array (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Shape of the array: (4, 3)
Type of the array: <class 'numpy.ndarray'>
Data type of the array elements: int32


In [3]:
arr_c = np.array([[3, -2],
                  [1,  0]])

eigenvalues, eigenvectors = np.linalg.eig(arr_c)

print("\nGiven Matrix:\n", arr_c)
print("\nEigenvalues:\n", eigenvalues)
print("\nRight Eigenvectors:\n", eigenvectors)


Given Matrix:
 [[ 3 -2]
 [ 1  0]]

Eigenvalues:
 [2. 1.]

Right Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [4]:
arr_d = np.array([[0, 1, 2],
                  [3, 4, 5]])

diagonal_sum = np.trace(arr_d)

print("\nGiven Array:\n", arr_d)
print("\nSum of Diagonal Elements:", diagonal_sum)


Given Array:
 [[0 1 2]
 [3 4 5]]

Sum of Diagonal Elements: 4


In [5]:
arr_e = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])

reshaped_e = arr_e.reshape(2, 3)

print("\nOriginal Array (3x2):\n", arr_e)
print("\nReshaped Array (2x3):\n", reshaped_e)


Original Array (3x2):
 [[1 2]
 [3 4]
 [5 6]]

Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]
